(2)Waiting for exam.
Folganoid/FGframe pull request #2
Opened 2017-03-24 11:03 UTC by Folganoid

2017-04-02 08:41 UTC, Artiomtb requested changes
1 - а чего меняется реквест с пулл реквестом по валидатору?
2 - а где валидационные рулы и их использование?

2017-04-02 08:41 UTC, Artiomtb commented on src/Controller/Controller.php
> +        if (Validation::isJSON($content)) {
не думаю, что isJson() подходит к валидатору.

2017-04-02 17:44 UTC, Folganoid commented on src/Controller/Controller.php
> +        if (Validation::isJSON($content)) {
Валидационные правила у меня прошиты регулярками в конфиге на стороне магазина, а isJSON() да, перекину в контроллер.

2017-05-06 07:03 UTC, Artiomtb approved these changes
Мержи

2017-05-06 07:03 UTC, Artiomtb commented on src/App.php
> +        // $this->config = Validation::checkConfigFile(ROOTDIR . '/config/router.php');
?

2017-05-06 07:03 UTC, Artiomtb commented on src/App.php
> +        //$request = new Request();
?

2017-05-06 17:25 UTC, merged

2017-05-21 07:49 UTC, ddavidov commented on src/DataBase/MysqlDataBaseDriver.php
> +class MysqlDataBaseDriver extends PostgresqlDataBaseDriver
мммм..... трошки нонсенс тут получается. С т.з. архитектуры должен быть абстрактный базовый например SqlDriver а от него мы наследуем уже MysqlDataBaseDriver и PostgresqlDataBaseDriver . А не друго от друга.

2017-05-21 07:49 UTC, ddavidov commented on src/Middleware/Test1.php
> +<?php
Думаю, в мастер это попадать не должно. По кр. мере в таком виде.

2017-05-25 19:29 UTC, Folganoid commented on src/Middleware/Test1.php
> +<?php
всё пофиксил